---
- name: Setup WebServers
  hosts: websrvgrp
  become: yes
  tasks:
    - name: Install Apache httpd
      yum: 
        name: httpd
        state: present
    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Copy Index.html to DbServers
      copy:
        src: index.html
        dest: /var/www/html/index.html

- name: Setup DbServers
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: Install mysql
      yum: 
        name: mariadb-server
        state: present
    - name: Start and enable mysql
      service:
        name: mariadb
        state: started
        enabled: yes
  